import type { Metadata } from "next";
import { Vazirmatn } from "next/font/google";
import { RootProvider } from 'fumadocs-ui/provider';
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";

import type { Translations } from 'fumadocs-ui/i18n';

const vazirmatn = Vazirmatn({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const locales = [
  {
    name: 'فارسی',
    locale: 'fa',
  },
];


const cn: Partial<Translations> = {
  search: 'جستجو',
  toc: "کاوش در صفحه",
  nextPage: "صفحه بعدی", 
  previousPage: "صفحه قبلی", 
  searchNoResult: "هیچ داده‌ای مطابق جستجوی شما نیست",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" className="dark" suppressHydrationWarning>
      <body className={vazirmatn.className} dir="rtl">
         <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <RootProvider
              i18n={{
                  locale: "fa",
                  locales,
                  translations: cn
              }}
              dir="rtl"
              >
              {children}
            </RootProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
